# config/sidekiq.yml

:concurrency: 10

:queues:
  - [onclass_comunity_Mentions, 1]
  - [onclass_comunity_pdca_students, 1]
  - [onclass_students_data, 1]
  - [lme_line_inflows, 1]
  - [lme_line_counts, 1]
  - [youtube_analytics, 1]
  - [youtube_competitors, 1]
  - [default, 1]
